# Generated by Django 5.2.1 on 2025-06-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_disponibilites_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('en attente', 'En attente'), ('confirmé', 'Confirmé'), ('annulé', 'Annulé')], default='en attente', max_length=50),
        ),
    ]
