# Generated by Django 5.2.1 on 2025-06-27 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_rendezvous_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteRendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('contenu', models.TextField()),
                ('diagnostic', models.TextField()),
                ('rendez_vous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_rendus', to='blog.rendezvous')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
